### ISSUE TITLE
Wrong brew install instructions on Speakyeasy Overlays docs

### ISSUE THREAD

**Issue by philsturgeon** [speakeasy-api/openapi-overlay#5]
I know this isn't the right repo but I couldn't find the right one. 

The speakeasyapi.dev docs (https://www.speakeasyapi.dev/docs/openapi/overlays) were telling me to do `brew install speakeasy-cli` which didn't work, elsewhere in docs suggested `brew install speakeasy-api/homebrew-tap/speakeasy` which did. 

<img width="810" alt="image" src="https://github.com/speakeasy-api/openapi-overlay/assets/67381/f37cc7b1-e902-4f56-b25b-d3b4a7ae9b7d">

**Comment by philsturgeon** [comment]
Whilst I'm talking about this page, >> is append, you probably want to use > here, as I was appending each attempt onto the end of the existing `combined.yaml` and it was making me think it wasn't working. It was, just... further down the file. 

<img width="566" alt="image" src="https://github.com/speakeasy-api/openapi-overlay/assets/67381/615bc751-bf09-4045-9866-532e37afb307">

**Comment by TristanSpeakEasy** [comment]
Thanks Phil for the issue, and sorry for the delay seems to have been missed over the XMAS period.

@AshGodfrey FYI
