### ISSUE TITLE
Feature request: Log a warning when a target expression doesn't match anything

### ISSUE THREAD

**Issue by hkosova** [speakeasy-api/openapi-overlay#7]
When writing JSONPath expressions, it's common to make mistakes where the expression is syntactically valid but matches nothing. Currently `speakeasy overlay apply` just silently ignores such targets (regardless of `--logLevel`), which complicates troubleshooting.

It would be nice if the tool could warn the user about such noop targets. These warnings could be either always on, or enabled by some flag.

<br/>

Some common errors:

1. Typos in node names, values, filters:

```
$..parameters[?( @.name == 'fron_date' )]

$..paramaters[?( @.name == 'from_date' )]

$.servers[?( @.descripton == 'Dev' )]
```

2. Skipping nodes in a path:

```yaml
- target: $.components.schemas.SchemaName.propName
  update:
    description: something
    example: 123
```

Correct version:

```
- target: $.components.schemas.SchemaName.properties.propName
```

3. Extra nodes in a path
```yaml
$.paths.*[?( @.operationId == 'get_foo' )].get   # `.get` is not needed here
```

---
Edit: another use case - consider an overlay that targets endpoints 

```yaml
$.paths['/foos/{id}'].get

$.paths.*[?( @.operationId == 'get_foo' )]
```
but then the endpoint gets renamed (e.g. `/foos/{id}` becomes `/foos/{foo_id}`), or its `operationId` gets changed (e.g. maybe op IDs are autogenerated and the algorithm changes).

As an overlay author and maintainer, I would like to get notified about non-matches so that I can update the overlay to match the current state of my API.

**Comment by ThomasRooney** [comment]
We've implemented a strict mode in https://github.com/speakeasy-api/openapi-overlay/pull/9 which will be applied with `speakeasy overlay apply --strict` and give a reasonable error if there are no nodes that matches a particular `target` expression in #9
